### ISSUE TITLE
Subquery returns more than 1 row for multiple Faculty Roles

### ISSUE THREAD

**Issue by devanshgoenka97** [lugnitdgp/nitdgp_website#13]
When multiple Faculty Roles are defined for one Faculty, an OperationalError with message 'Subquery returns more than 1 row" is encountered.

**Comment by ankan17** [comment]
![screenshot from 2018-02-04 18-46-58](https://user-images.githubusercontent.com/25361275/35795625-b8340626-0a7f-11e8-8f02-057d30d27245.png)
