### ISSUE TITLE
CORS origin error for fa-icons, taking too much time to load

### ISSUE THREAD

**Issue by arnav-amb** [lugnitdgp/nitdgp_website#20]

**Comment by arnav-amb** [comment]
@Compro-Prasad update?

**Comment by ankan17** [comment]
Why was this issue closed?

**Comment by ankan17** [comment]
Still not solved for the webpack dev server. Reopening it. Here is a screenshot:

![screenshot from 2018-03-27 12-55-10](https://user-images.githubusercontent.com/25361275/37953054-62c818f0-31bf-11e8-9e22-0585b29c6afc.png)

**Comment by Compro-Prasad** [comment]
@ankan17 Still getting CORS?
