### ISSUE TITLE
Inconsistent height of homepage carousel

### ISSUE THREAD

**Issue by ankan17** [lugnitdgp/nitdgp_website#26]
Currently, the height of the carousel images is inconsistent i.e., changes according to the height of the image. Everything needs to be of the same height.

**To reproduce:**
Run the webpack development server and see the carousel.

**Write any new style required in the carousel component's style section itself.**

**Comment by arnav-amb** [comment]
Issue fixed via fbeb08eee6c4079bb686adc7038ba0e7e5c30772
