### ISSUE TITLE
Backup strategy for data contained in the database

### ISSUE THREAD

**Issue by Compro-Prasad** [lugnitdgp/nitdgp_website#29]
We need to come up with some backup strategy to backup database and the files.

**Comment by ankan17** [comment]
Running a cronjob on a daily basis to take a dump of the database every day should do the trick I think. @Compro-Prasad @ghoshbishakh

**Comment by Compro-Prasad** [comment]
Can we have different revisions of the backup? Who knows which might be the correct state at what point of time! If it is a yes then are there some tools to perform this job?

**Comment by Compro-Prasad** [comment]
We also need a procedure to apply/restore the backup in critical conditions.

**Comment by devanshgoenka97** [comment]
Addressed to, using Crontab and Dbbackup
