### ISSUE TITLE
Port all static pages to Vue JS

### ISSUE THREAD

**Issue by Compro-Prasad** [lugnitdgp/nitdgp_website#31]

**Comment by ankan17** [comment]
What is this? -_- Close this issue and open more granular issues if the intention is to keep track of wrk done! Otherwise we all know that all static pages have to be ported to Vue.

**Comment by ankan17** [comment]
Better yet we should create a project for this one.

**Comment by Compro-Prasad** [comment]
This issue signifies that work is still left and we need to close this issue as soon as possible.

**Comment by ankan17** [comment]
Create a project for this one and individual issues for every page. That way we can keep track in a better way.

**Comment by arnav-amb** [comment]
Should i include tmp_ files which are currently static but would later be made dynamic?

**Comment by arnav-amb** [comment]
For now i am including all such static files.We should later make it dynamic.Will open an issue regarding it soon.

**Comment by arnav-amb** [comment]
Porting finished https://github.com/lugnitdgp/nitdgp_website/commit/e6f58f340d1b06c3a69366559e04e8714f08b3e8
