### ISSUE TITLE
Stick footer to the bottom of the page

### ISSUE THREAD

**Issue by ankan17** [lugnitdgp/nitdgp_website#35]
Whatever be the height of the content, the footer should always be at the bottom of the page which currently is not. Here is a screenshot for reference (see the whitespace at the bottom):

![screenshot from 2018-03-31 12-43-17](https://user-images.githubusercontent.com/25361275/38160860-730e1fe6-34e1-11e8-81b9-8568b1351b04.png)

**Make the style changes in the vue components' style section.**

**Comment by Compro-Prasad** [comment]
Setting it as `bottom: 0` should solve the problem.

**Comment by Compro-Prasad** [comment]
https://github.com/lugnitdgp/nitdgp_website/commit/0366b18e8a473d741c22e08d442b739b434bc772
