### ISSUE TITLE
Load data from the server

### ISSUE THREAD

**Issue by arnav-amb** [lugnitdgp/nitdgp_website#37]
For now, I only have ported all static HTML to almost static Vue files. This has to be fixed by loading dynamic data from the server. All checked boxes are done. Details about the page are in parenthesis:
* [x] Individual Department
* [x] Individual Faculty
* [x] Academics
  * [x] Admission
  * [x] Calendar
  * [x] Convocation
  * [x] Departments
  * [x] Documents
  * [x] Exams
  * [x] Notices (List of three tabs corresponding to three type of notices - General, Student, Academic)
  * [x] Registrations
  * [x] Regulations
* [x] Administration
  * [x] Visitor
  * [x] MHRD
  * [x] Chairperson (Same as director)
  * [x] BOG (List of Person cards)
  * [x] Director (Person card)
  * [x] Registrar (Person card)
  * [x] BWC/IFC (List of lists)
  * [x] Senate (List of lists)
  * [x] HODs (List of Person cards)
  * [x] Deans (List of Person cards)
* [x] Activities
  * [x] Achievements (List of links)
  * [x] Seminar and Events (Type-notices)
  * [x] Outreach
  * [x] Research (List of lists)
  * [x] Students
* [x] Information
  * [x] Reports (List of lists)
  * [x] Accounts (List of lists)
  * [x] Careers (Type-notices)
  * [x] Tenders (Type-notices)
  * [x] TEQIP (List of lists)
  * [x] RTI (List of lists)
  * [x] NIRF (List of lists)
  * [x] NBA (List of lists)
  * [x] Chanakya
  * [x] e-Prashasan
  * [x] Public Grievances
  * [x] History
  * [x] Location
  * [x] More (List of lists)
* [x] Facilities

**Comment by ankan17** [comment]
@arnav-amb Open individual issues regarding which pages have to be made dynamic

**Comment by arnav-amb** [comment]
@Compro-Prasad @ankan17 Please finish this ASAP

**Comment by arnav-amb** [comment]
# ALL DONE !
