### ISSUE TITLE
Check for the filetype being uploaded as carousel image

### ISSUE THREAD

**Issue by ankan17** [lugnitdgp/nitdgp_website#45]
Presently no check is implemented to prevent unsupported image file types from being uploaded. There needs to be a proper check.

**Comment by devanshgoenka97** [comment]
@ankan17  An Image Field allows only JPG, PNG or other supported Image types to be uploaded. No additional checking is required.

**Comment by Compro-Prasad** [comment]
@devanshgoenka97 what about PDF?

**Comment by devanshgoenka97** [comment]
Why will you upload a PDF as Carousel Image?

**Comment by Compro-Prasad** [comment]
No, in notices.

**Comment by devanshgoenka97** [comment]
Check the issue. It says check the file type in Carousel Image.
