### ISSUE TITLE
Fields still left for faculty

### ISSUE THREAD

**Issue by Compro-Prasad** [lugnitdgp/nitdgp_website#46]
+ Education
+ Work Experience
+ Projects
+ Publications - 3 types namely: Journal(table), Conference(table), Books/Patents(links)
+ Teachings - Which semester is he teaching and the subjects
+ Students working under him
+ Recognitions
+ Administrative Responsibilities
+ Contact info - Email, Phone, Address

See http://nitdgp.ac.in for more details

**Comment by arnav-amb** [comment]
@devanshgoenka97 reference for faculty API
