### ISSUE TITLE
Fix Notice Type in Notices

### ISSUE THREAD

**Issue by devanshgoenka97** [lugnitdgp/nitdgp_website#51]
Hashes starting from 8e are Student,
d2 are Academic and 7 is General.

**Comment by Compro-Prasad** [comment]
This is taken care in the frontend. See https://github.com/lugnitdgp/nitdgp_website/commit/b179492c5f93094a35e43da3418623b3094f6c76 .
The other hashes are not implemented yet. Only the Student notices because others contain dummy information.
