### ISSUE TITLE
Porting data to PostgreSQL

### ISSUE THREAD

**Issue by arnav-amb** [lugnitdgp/nitdgp_website#55]
According to [Django Documentation](https://docs.djangoproject.com/en/2.0/topics/migrations/) PostgreSQL is quite better than MySQL. But we already have data in mysql. So, for better migrations and rollbacks we need to switch to PostgreSQL.

**Comment by devanshgoenka97** [comment]
Is this necessary? The MySQL database is not posing any issues and we already have a lot of data present on the server.

**Comment by Compro-Prasad** [comment]
I don't know whether we would be adding/removing features in the future. But if we do it will become a mess. As stated on the Django Documentation, MySQL isn't nice to Django migrations which I have already experienced earlier.

**Comment by devanshgoenka97** [comment]
Closing this as currently we cannot do this.
It can be discussed during Phase 2

**Comment by Compro-Prasad** [comment]
https://pgloader.io/about/ does it.
