### ISSUE TITLE
Move Home page details to frontend

### ISSUE THREAD

**Issue by Compro-Prasad** [lugnitdgp/nitdgp_website#60]
Currently there is a specific database for different college sections and tiles. This could be removed completely from backend as it is a bit repetitive to maintain both UI and data separately. Only the carousel images and newsfeed can be fetched as they are purely dynamic in nature.

**Comment by devanshgoenka97** [comment]
Why?

The main purpose of that was to maintain the dynamic nature of tiles and
sections.

**Comment by Compro-Prasad** [comment]
The UI state is dependant upon the amount of data. Further more, the change in amount of data will affect the UI. Sections are currently the most vulnerable. The inner tiles are less vulnerable but that is totally dependant on the data itself. So, a change in data will affect the UI. Thus the frontend team will have to be indirectly involved with the change in data on the server. And the tile data will not change so frequently.
So, it would be better to rely currently on the frontend team for the change in data. In near future a better dynamic design will be picked up and then we can easily go for requesting data from the server.

**Comment by arnav-amb** [comment]
@Compro-Prasad We can think about this in the next version of the website but in any case tiles and sections will always be dynamic.
