### ISSUE TITLE
New issues

### ISSUE THREAD

**Issue by ankan17** [lugnitdgp/nitdgp_website#63]
- [x] Add new notices
- [x] In mobile view, the collapsed title of homepage tiles should be left aligned with a down arrow on right: https://github.com/lugnitdgp/nitdgp_website/commit/5e5ee6699331b7fcd16a8ea2e2706ccc9dfc87ba
- [x] Change style of HOD page to make it similar to the Director page: Not a priority, thus not required
- [x] Hide {} for empty data in people page: https://github.com/lugnitdgp/nitdgp_website/commit/1df39f14c3b933e88fb1bbaf6f2418564979e0e2
- [x] Remake Faculty page: https://github.com/lugnitdgp/nitdgp_website/commit/adfdad2fe1e861dffe2918409ba974f3bdc25769 https://github.com/lugnitdgp/nitdgp_website/commit/3b2df184398b6cb89c18c05753c4f65e80fe56d9
- [x] Add footer links to government websites: https://github.com/lugnitdgp/nitdgp_website/commit/3b51bac15e1fddc142ab025ec4007cb845af6e6d
- [x] Increase font size of header (NIT Durgapur): https://github.com/lugnitdgp/nitdgp_website/commit/2d10d740cdc0730d547e50d82d12a4d8a4fdfa3a
- [ ] Add content for Archives and policies(currently static): Opened as #77
- [ ] Add page for Computer Center: Opened as #78
- [x] Fix top padding for Error 404 page and contacts page: https://github.com/lugnitdgp/nitdgp_website/commit/b8a2e20e5d52e591b9da90b8909321daf359e340
- [x] Reduce size of Carousel Images in home page: Done in the backend(not yet automated).

**Comment by arnav-amb** [comment]
@Compro-Prasad  Update the contacts page first. Take reference from here: http://nitdgp.ac.in/contact_us.php

**Comment by arnav-amb** [comment]
@divyanshumehta  Please help @Compro-Prasad compro with these issues

**Comment by arnav-amb** [comment]
@Compro-Prasad report your work in the checklist
