### ISSUE TITLE
Top bar is not responsive

### ISSUE THREAD

**Issue by ankan17** [lugnitdgp/nitdgp_website#64]
The top navbar breaks in smaller screens. Also the home link needs to be in the top bar.

**Comment by arnav-amb** [comment]
@Compro-Prasad is looking into it. @Compro-Prasad Add a dropdown menu as discussed ASAP

**Comment by Compro-Prasad** [comment]
https://github.com/lugnitdgp/nitdgp_website/commit/0716412f7cd6e28423fa8a82235fe97e32dda02c
