### ISSUE TITLE
Tile Orientation

### ISSUE THREAD

**Issue by glugnitdgp** [lugnitdgp/nitdgp_website#73]
The tiles are disoriented for most sections.

**Comment by divyanshumehta** [comment]
Done

**Comment by Compro-Prasad** [comment]
Put commit id and close this issue if done @divyanshumehta .

**Comment by Compro-Prasad** [comment]
https://github.com/lugnitdgp/nitdgp_website/commit/de68f47eebe8db240cbbdc01b65a365700793089
